# Simple yaml config-driven schema which is used to define model attributes,
# index key names, and form properties.
#
# Attributes must have a type but all other configuration options are optional.
# Please note: If using Valkyrie's Fedora Metadata Adapter, predicates for attributes
# must be placed here.
#
# attributes:
#   attribute_name:
#     type: string
#     multiple: false
#     index_keys:
#       - "attribute_name_sim"
#     form:
#       required: true
#       primary: true
#       multiple: false
#
# @see config/metadata/basic_metadata.yaml for an example configuration
#
# Generated via
#  `rails generate hyrax:work_resource CdlResource`

attributes:
  creator:
    type: string
    multiple: true
    form:
      required: true
      primary: true
    index_keys:
      - "creator_sim"
      - "creator_tesim"
    predicate: http://purl.org/dc/elements/1.1/creator
  keyword:
    type: string
    multiple: true
    form:
      required: true
      primary: true
    index_keys:
      - "keyword_sim"
      - "keyword_tesim"
    predicate: http://schema.org/keywords
  resource_type:
    type: string
    multiple: true
    form:
      required: true
      primary: true
    index_keys:
      - "resource_type_sim"
      - "resource_type_tesim"
    predicate: http://purl.org/dc/terms/type
  rights_statement:
    type: string
    multiple: true
    form:
      required: true
      primary: true
    index_keys:
      - "rights_statement_sim"
      - "rights_statement_tesim"
    predicate: http://www.europeana.eu/schemas/edm/rights
  license:
    type: string
    multiple: true
    form:
      primary: false
    index_keys:
      - "license_sim"
      - "license_tesim"
    predicate: http://purl.org/dc/terms/license
  abstract:
    type: string
    multiple: true
    form:
      primary: false
    index_keys:
      - "abstract_sim"
      - "abstract_tesim"
    predicate: http://purl.org/dc/terms/abstract
  access_right:
    type: string
    multiple: true
    form:
      primary: false
    index_keys:
      - "access_right_sim"
      - "access_right_tesim"
    predicate: http://purl.org/dc/terms/accessRights
  additional_information:
    type: string
    predicate: http://purl.org/dc/terms/accessRights
    multiple: true
    form:
      primary: false
    index_keys:
      - "additional_information_tesim"
  admin_note:
    type: string
    form:
      primary: false
    predicate: http://schema.org/positiveNotes
    multiple: false
    index_keys:
      - "admin_note_tesim"
  alternative_title:
    type: string
    multiple: true
    form:
      primary: false
    index_keys:
      - "alternative_title_sim"
      - "alternative_title_tesim"
    predicate: http://purl.org/dc/terms/alternative
  bibliographic_citation:
    type: string
    predicate: http://purl.org/dc/terms/bibliographicCitation
    multiple: true
    form:
      primary: false
    index_keys:
      - "bibliographic_citation_tesim"
  chronology_note:
    type: string
    predicate: https://hykucommons.org/terms/chronology_note
    multiple: true
    form:
      primary: false
    index_keys:
      - "chronology_note_tesim"
      - "chronology_note_sim"
  contributing_library:
    type: string
    predicate: https://hykucommons.org/terms/contributing_library
    multiple: true
    form:
      primary: false
    index_keys:
      - "contributing_library_tesim"
      - "contributing_library_sim"
  contributor:
    type: string
    multiple: true
    form:
      primary: false
    index_keys:
      - "contributor_tesim"
      - "contributor_sim"
    predicate: http://purl.org/dc/elements/1.1/contributor
  date_created:
    type: date_time
    multiple: true
    form:
      primary: false
    index_keys:
      - "date_created_sim"
      - "date_created_tesim"
    predicate: http://purl.org/dc/terms/created
  description:
    type: string
    multiple: true
    form:
      primary: false
    index_keys:
      - "description_sim"
      - "description_tesim"
    predicate: http://purl.org/dc/elements/1.1/description
  identifier:
    type: string
    multiple: true
    form:
      primary: false
    index_keys:
      - "identifier_sim"
      - "identifier_tesim"
    predicate: http://purl.org/dc/terms/identifier
  language:
    type: string
    multiple: true
    form:
      primary: false
    index_keys:
      - "language_sim"
      - "language_tesim"
    predicate: http://purl.org/dc/elements/1.1/language
  library_catalog_identifier:
    type: string
    predicate: https://hykucommons.org/terms/library_catalog_identifier
    multiple: true
    form:
      primary: false
    index_keys:
      - "library_catalog_identifier_tesim"
      - "library_catalog_identifier_sim"
  publisher:
    type: string
    multiple: true
    form:
      primary: false
    index_keys:
      - "publisher_sim"
      - "publisher_tesim"
    predicate: http://purl.org/dc/elements/1.1/publisher
  related_url:
    type: string
    multiple: true
    form:
      primary: false
    index_keys:
      - "related_url_sim"
      - "related_url_tesim"
    predicate: http://www.w3.org/2000/01/rdf-schema#seeAlso
  rights_notes:
    type: string
    multiple: true
    form:
      primary: false
    index_keys:
      - "rights_notes_sim"
      - "rights_notes_tesim"
    predicate: http://purl.org/dc/elements/1.1/rights
  source:
    type: string
    multiple: true
    form:
      primary: false
    index_keys:
      - "source_sim"
      - "source_tesim"
    predicate: http://purl.org/dc/terms/source
  subject:
    type: string
    multiple: true
    index_keys:
      - "subject_sim"
      - "subject_tesim"
    form:
      primary: false
    predicate: http://purl.org/dc/elements/1.1/subject
  bulkrax_identifier:
    type: string
    predicate: https://hykucommons.org/terms/bulkrax_identifier
    multiple: false
    index_keys:
      - "bulkrax_identifier_tesim"
      - "bulkrax_identifier_sim"
  arkivo_checksum:
    type: string
    multiple: false
    predicate: http://scholarsphere.psu.edu/ns#arkivoChecksum
  based_near:
    type: string
    multiple: true
    index_keys:
      - "based_near_sim"
      - "based_near_tesim"
    predicate: http://xmlns.com/foaf/0.1/based_near
  import_url:
    type: string
    predicate: http://scholarsphere.psu.edu/ns#importUrl
  label:
    type: string
    index_keys:
      - "label_sim"
      - "label_tesim"
    predicate: info:fedora/fedora-system:def/model#downloadFilename
  relative_path:
    type: string
    predicate: http://scholarsphere.psu.edu/ns#relativePath
